### ISSUE TITLE
Erroneous error message about tag nesting

### ISSUE THREAD

**Issue by RolfKyburz** [mibuthu/wp-event-list#118]
if lists are used in the event description (&lt;ul&gt; or &lt;ol&gt;), the list display shows an error

> Warning: Not properly nested tag found (last opening tag: div, closing tag: p) in /home/rolfmu76/www/rolf-musicblog.net/wp-content/plugins/event-list/includes/db.php on line 335

even though the HTML is correct, and I'm not even using &lt;div&gt; nor &lt;p&gt; tags at all. I suspect that any nested tags (not just &lt;li&gt; inside &lt;ul&gt;) will produce such errors. The error is harmless, as the events all display properly, but the error message still looks odd.

**Comment by mibuthu** [comment]
I cannot reproduce this issue. Can you provide a sample entry for testing?

**Comment by RolfKyburz** [comment]
Thanks for getting back to me on this. I am currently traveling, but will try finding examples when I am back, in a week or two.
