### ISSUE TITLE
Plugin appears to be removed from the official registry

### ISSUE THREAD

**Issue by leonardehrenfried** [mibuthu/wp-event-list#123]
If you visit https://wordpress.org/plugins/event-list/ you are redirect to a search page for "event list" instead.

Is this intentional or an oversight?

Thanks for a great plugin, BTW!

**Comment by mibuthu** [comment]
The plugin was temporarily closed by wordpress due to a security vulnerability. I have fixed this issue in 0.7.9, so it should be back online soon. They have written that the review can take 4-5 working days.
