### ISSUE TITLE
All Events admin filters redirect to a 404 page

### ISSUE THREAD

**Issue by sivinjski** [mibuthu/wp-event-list#126]
Event List (v0.7.9) admin suddenly started to redirect to a default 404 page of the website when any filter on "All Events" admin page is selected and "Filter" button is clicked. Although the URL still redirects from ".../wp-admin/admin.php?page=el_admin_main" to ".../wp-admin/admin.php?page=el_admin_main&_wpnonce=a3d64e1d42&_wp_http_referer=%2Fwp-admin%2Fadmin.php%3Fpage%3Del_admin_main&date=past&cat=all&noheader=true&filter=Filter&paged=1".

Anyone else experiencing the same issue?

**Comment by mibuthu** [comment]
I can reproduce the problem in some of my installations, but only in a few of them.
So I can have a look what causes this issue.

**Comment by mibuthu** [comment]
Should be fixed with using custom post types in 0.8.0 (see #132).
