### ISSUE TITLE
Contact to report security vulnerabilities

### ISSUE THREAD

**Issue by PluginVulnerabilities** [mibuthu/wp-event-list#128]
We haven't been able to find an email address or some other way we can privately report a couple of security vulnerabilities we found in this plugin. Is there something like that available or should we just submit those here?

**Comment by mibuthu** [comment]
Yes, you can place it here.

**Comment by PluginVulnerabilities** [comment]
During our monitoring of changes made to WordPress plugins we found a PHP object injection vulnerability and a related cross-site request forgery (CSRF) vulnerability in the plugin.

In the file /admin/includes/admin-import.php the function import_events() passes the value of the POST input "reviewed_events" through the unserialize() function:

    $reviewed_events = unserialize(stripslashes($_POST['reviewed_events']));

An attacker can abuse that to cause PHP object injection to occur, https://www.owasp.org/index.php/PHP_Object_Injection

Using JSON encoding and decoding is one alternative method to accomplish the same thing while avoiding this type of vulnerability.

When doing an import in the plugin there is no protection against cross-site request forgery (CSRF). You can find information on preventing cross-site request forgery (CSRF) in WordPress plugins at http://codex.wordpress.org/WordPress_Nonces.
