### ISSUE TITLE
Not published anymore?

### ISSUE THREAD

**Issue by kaffeeringe** [mibuthu/wp-event-list#129]
Hej!

I can't find WP-Event-List in the plugin repository anymore:
https://wordpress.org/plugins/search/event-list/

Is that intentional?

For my purpose your plugin is the best! Please keep it alive! ;-)

**Comment by mibuthu** [comment]
Hi,
there was a security vurnerability found, so wordpress disabled the plugin until this is fixed.
I have released a new version with these fixes yesterday, so I hope the plugin will be back only soon.
