### ISSUE TITLE
0.7.11 | Server Error 500

### ISSUE THREAD

**Issue by w00dst0ck** [mibuthu/wp-event-list#130]
After the update to 0.7.11 I've two problems.

* The wordpress admin page could not be opend. It results in server error 500.
* The short code "[event-list]" does not work

The downgrade to 0.7.10 fixes the Server error but the short code won't work anymore.

Any idea to fix that?

Best regards,
Kai

**Comment by mibuthu** [comment]
There are some issues with the actual version. If you want to downgrade until a fixed version is released you have to downgrade to 0.7.9.
I think you have the same issue as described [here](https://wordpress.org/support/topic/fatal-error-2695/). But there are some more issues. I will try to release a fixed version a soon as possible.

**Comment by mibuthu** [comment]
I have release a new version 0.7.12 now. I think also your issue should be fixed with this version.

**Comment by w00dst0ck** [comment]
Thanx for that fast fix!
