### ISSUE TITLE
bad upgrade log filename 'wp-contentevent-list_upgrade.log'

### ISSUE THREAD

**Issue by zu2** [mibuthu/wp-event-list#155]
The upgrade log should be recorded into wp-content/event-list_upgrade.log,
but it created to wp-contentevent-list_upgrade.log.

Add '/' after WP_CONTENT_DIR.

https://github.com/zu2/wp-event-list/commit/33c532c5f6053d5032b93f765489dd5e48c86185

**Comment by mibuthu** [comment]
Thanks for the info, I will release a fixed version soon.
