### ISSUE TITLE
Error on csv import - possible issue with create_function and PHP 7.2 or higher?

### ISSUE THREAD

**Issue by nteuscher** [mibuthu/wp-event-list#157]
I'm getting an error when using the csv import function. I have even tried importing the example file (with existing data and using future data) and get the same error. The error says "Event from CSV-line : Saving of event failed!" for every event. I am running PHP 7.3.26 and browsing the code for admin-import.php I noticed that that specific error message "Saving of event failed!" comes from that code. I also noticed that 'create_function' is used two times. I believe that has been deprecated as of PHP 7.2. Perhaps this is leading to the problem?

Here are the code lines where it is included ... 
line 146
`$import_data = array_filter($import_data, create_function('$v', 'return !is_wp_error($v)'));`
line 306
`array_walk($event, create_function('&$v', '$v = is_array($v) ? array_map("trim", $v) : trim($v);'));`

Perhaps these lines could be revised to fix the problem with the import? (I'm not smart enough to fix the code ... and I'm not even sure this is the issue)

**Comment by nteuscher** [comment]
OK ... a bit more investigating found the following ... The error is not with the code noted above (although create_function has been deprecated). I tracked the actual error down to the point at which the post is updated in the wordpress database. The failure occurs at the following line of code in event.php:
`$pid = wp_insert_post($postdata);`

I added the following code to extract the error:
`$pid = wp_insert_post($postdata, $wp_error = true);
		if(!is_wp_error($pid)){
			//the post is valid
		}else{
			//there was an error in the post insertion, 
			echo $pid->get_error_message();
			echo " " ."<br>";
			print_r($postdata);
		    echo " " ."<br>";
		}`

The result when importing the example data file is:
Array ( [post_status] => publish [post_title] => Cycling [post_excerpt] => [post_content] => This is a test entry. )
Could not insert post into the database.
Array ( [post_status] => publish [post_title] => Cycling [post_excerpt] => [post_content] => This is a test entry. )
ERROR: Post not found!

I'm not sure why there is an error in inserting the post into the database. There appears to be all of the required information; however, it gives an error.

**Comment by mibuthu** [comment]
Thanks for the investigations.

As you already mentioned `create_function` should not be a problem in PHP up to 7.4 (should only be a warning) but it is an issue with PHP 8, so it has to be fixed anyway.

I haven't tested myself yet, but I assume the problem must be caused by the new excerpt functionality.
I will have a detailed look in the next days and will reply.

**Comment by mibuthu** [comment]
The changes in 03423b28b5a81df866c6c203b71f1457b15475b1 should fix this issue.
