### ISSUE TITLE
Error handling of event start date causes failure

### ISSUE THREAD

**Issue by TimSmith** [mibuthu/wp-event-list#160]
$this is being used in a static method save_postmeta in /includes/event.php when attempting to handle a missing start date. It causes the event insert/update to fail and generates the following error:
`PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object in /wp-includes/class-wp-hook.php on line 294`

To trigger enter an event start date before 1970.

Note that just swapping &$this to __CLASS__ won't work as the callable function on the 'redirect_post_location' filter requires access to the $errors variable.

**Comment by mibuthu** [comment]
Fixed with 9f770ee2ef24c8d36d68c2ad42ac479f0987e663
