### ISSUE TITLE
Can't access draft / template entries

### ISSUE THREAD

**Issue by RolfKyburz** [mibuthu/wp-event-list#163]
I'd like the ability to prepare eventlist entries, i.e., to have a set of templates, and / or to be able to leave draft entries, i.e., to abandon editing temporarily without posting the entry just yet. This _seems_ to work, and my admin interface indeed shows
         All (371) | Published (365) | Drafts (6) | ...
However, when I select the "Draft" link, the interface shows an empty list, with "No events found". When I select "All", I don't see the complete set of 371 entries, but just the 365 published ones. In fact, the Draft items seem to be there, but I have not found any means to access them. Really odd... this issue has been nagging me for several years already and persists up to version 0.8.6 / WP 5.8.3

**Comment by mibuthu** [comment]
Should be fixed with 557b5493745d076a5831179126951c2d85b38c51
