### ISSUE TITLE
li.event causing rendering problems

### ISSUE THREAD

**Issue by hellocatfood** [mibuthu/wp-event-list#89]
I'm having rendering issues of this plugin on my site: http://www.hellocatfood.com/events/ there is a big gap before the events display. Screenshot: http://imgur.com/nsxkEhx

it seems that disabling `clear: both;` on li.event fixes this issue. Can this be changed in the main plugin or will it cause breakages?

**Comment by mibuthu** [comment]
Sorry but in my installations (e.g. with Twenty Twelve theme) the layout will break when I remove this line.

**Comment by hellocatfood** [comment]
Do you have a live site I can verify this on? I've tried with a local installation (twenty twelve them) and disabling clear:both or changing it to clear:right doesn't break it.

I'm just trying to figure out what in my theme (touchfolio) could be causing this problem.
