### ISSUE TITLE
The date cannot be selected before Oct 4, 2020

### ISSUE THREAD

**Issue by yangray** [mibuthu/wp-event-list#98]
After the new update to 0.7.4, the event date selection can only be after Oct 4, 2020

**Comment by mibuthu** [comment]
Are you sure that you already updated to 0.7.4? There was a problem with 0.7.3 but it should be solved in 0.7.4.

**Comment by yangray** [comment]
Thanks for the reply. It did get upgraded to 0.7.4. But somehow it did not work. I did go back to check several days later, and this issue went away. I think it might be the issue with my browser cache. Thanks for the reply.
